<a href="https://colab.research.google.com/github/kokejohh/PMU_Module_1/blob/main/Copy_of_Pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS 101**
> ## *Author* : [Rathachai CHAWUTHAI](https://rathachai.creatier.pro/) , Ph.D
> ### *Affiliation* : Computer Engineering, King Mongkut's Institute of Technology Ladkrabang (KMITL)
> #### *Updated Date* : 2025-10-05
Learning by Pitchakorn Thiprangsi
---

> <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.



---

## Prerequisite Knowledge
> Python, List, Dictionary, Tuple, Function, Lambda, Numpy, and CSV


## Agenda

**Review**
*   Basic Python
*   About Dataset
*   Basic Numpy

**Pandas**
*   Series & Dataframe
*   Read CSV into a Pandas Dataframe
*   Column Selection
*   Row Selection
*   Row and Column Selection (1)
*   Cell Modification
*   Set Index
*   Row and Column Selection (2)
*   Reset Index
*   Range Selection
*   Conditinal Selection
*   Column Operation
*   New Column
*   Drop Row
*   Drop Column
*   Sorting (1)
*   Sorting (2)
*   Grouping (1)
*   Grouping (2)
*   Iteration
*   Apply Function
*   Save Dataframe into a CSV file


## Instruction

1.   Menu "File"
2.   "Save a Copy in Drive"



## Basic Python

In [ ]:
print('Hello World')

Hello World


In [ ]:
print('1 + 1 = ', 1+1, sep="_", end="a")

1 + 1 = _2a

In [ ]:
arr = [0, 10, 20, 30]

In [ ]:
arr[2] + arr[1]

30

In [ ]:
len(arr)

4

In [ ]:
for i in arr:
  print(i, end=' ')

0 10 20 30 

**Quiz !!**

> เขียน code เพื่อบวกเลขใน arr ทั้งหมด และแสดงคำตอบ

In [ ]:
# Answer
ans = 0
for i in arr:
  ans += i
print(ans)

print(sum(arr))

60
60


## About a Dataset

Click [https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv](https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv)

## Import Libraries

In [2]:

import numpy as np
import pandas as pd



## Basic Numpy

In [ ]:
[1,2,3] + [10,10,10]

[1, 2, 3, 10, 10, 10]

In [ ]:
[1,2,3] * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
print(np.array([1,2]) + 2)
print(np.array([1,2,3]))
np.array([2,4,6]) + np.array([1, 3, 5])

np.array([2, 4, 6]) * np.array([1, 3, 5])

[3 4]
[1 2 3]


array([ 2, 12, 30])

In [ ]:
np.array([1,2,3]) * 3

array([3, 6, 9])

In [ ]:
print(np.arange(5))
np.arange(10)

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [ ]:
print(np.random.rand(5))
print(np.random.randint(1, 10, 5))
print(np.random.randn(10))
arr = [1, 2, 3, 4, 5]
print(np.random.choice(arr, size=3))

np_arr = np.array([1,2,3,4])
np_arr2 = np_arr.view()
np.random.shuffle(np_arr)
print(np_arr)

np_arr2[0] = 9
print(np_arr)
print(np_arr2)

[0.80020381 0.4479649  0.20611137 0.38289859 0.35813888]
[4 9 5 9 6]
[ 0.74971328  0.59140458 -0.54640188  0.07463997  1.25658321  0.52130974
 -1.42941578 -0.84465903 -1.54625756 -0.49158582]
[4 3 2]
[2 3 4 1]
[9 3 4 1]
[9 3 4 1]


In [ ]:
np.random.randint(10,20,5)

array([14, 19, 14, 10, 17])

In [ ]:
print(np.zeros(10))
np.zeros(5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0.])

In [ ]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
np.ones(5)
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

**Quiz !!**

> แสดงคำตอบเป็น array ของเลข [3, 3, 3, 3, ..] จำนวน 20 ตัว

In [ ]:
# Answer
print(np.array([3] * 20)) # bad performance
print(np.full(20, 3)) # best performance
np.ones(20) * 3 # bare minimum

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3.])

In [ ]:
x = np.arange(0,5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x.sum()

np.int64(10)

In [ ]:
np.sum(x)

np.int64(10)

In [ ]:
x.mean()
np.mean(x)

np.float64(2.0)

In [ ]:
x.min()
np.min(x)

np.int64(0)

In [ ]:
x.max()

np.int64(4)

In [ ]:
x.std()
np.std(x)

np.float64(1.4142135623730951)

In [ ]:
x[0:3]

array([0, 1, 2])

In [ ]:
x[:3]

array([0, 1, 2])

In [ ]:
x[1:3]

array([1, 2])

In [ ]:
x[3:]

array([3, 4])

In [ ]:
x[-1]

np.int64(4)

In [ ]:
x[-2:]

array([3, 4])

In [ ]:
np.flip(x[-2:])

array([4, 3])

In [ ]:
import numpy as np
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
mat = np.array([[1, 2], [3, 4], [5, 6]])
print(mat.sum(axis=0))
print()
print(mat.sum(axis=1))
print()

arr = np.array([
    [[1, 2, 3],[4, 5, 6]],    # first “matrix”
    [[7, 8, 9],[10, 11, 12]]     # second “matrix”
])
print(arr.shape)  # (2, 2, 2)
print()
print(np.sum(arr, axis=0))
print()
print(np.sum(arr, axis=1))
print()
print(np.sum(arr, axis=2))



[ 9 12]

[ 3  7 11]

(2, 2, 3)

[[ 8 10 12]
 [14 16 18]]

[[ 5  7  9]
 [17 19 21]]

[[ 6 15]
 [24 33]]


**Quiz !!**

> จงใช้ numpy เพื่อบวกเลขตั้งแต่ 1 ถึง 20

In [ ]:
# Answer
np.arange(1, 21).sum()


np.int64(210)

## Pandas Series & Pandas Dataframe

In [ ]:
s1 = pd.Series([0, 10, 20, 5])
s1 = pd.Series(np.array([0, 10, 20]))

In [ ]:
s1

0     0
1    10
2    20
dtype: int64

In [ ]:
s1.mean()

np.float64(10.0)

In [ ]:
s1.max()

20

In [ ]:
s2 = pd.Series(["A", "B", "C"])

In [ ]:
s2

0    A
1    B
2    C
dtype: object

In [ ]:
df = pd.DataFrame({'name': s2, 'age': s1})
df

name  age
0    A    0
1    B   10
2    C   20

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
df['name']

0    A
1    B
2    C
Name: name, dtype: object

In [ ]:
type(df['name'])

pandas.core.series.Series

**Quiz !!**

> จงสร้าง Dataframe แบบนี้ด้วย Series

| Code  | From | To  |
|-------|------|-----|
| TG608 | HKT  | HKG |
| TG677 | NRT  | BKK |
| TG678 | BKK  | CAN |

In [ ]:
sA = pd.Series(['TG608', 'TG677', 'TG678'])
sB = pd.Series(['HKT', 'NRT', 'BKK'])
sC = pd.Series(['HKG', 'BKK', 'CAN'])

DF = pd.DataFrame({'Code': sA, 'From': sB, 'To': sC})
DF.to_csv('Flight.csv', index=False)

In [ ]:
DF

Code From   To
0  TG608  HKT  HKG
1  TG677  NRT  BKK
2  TG678  BKK  CAN

In [ ]:
df = pd.read_csv("Flight.csv")
df

Code From   To
0  TG608  HKT  HKG
1  TG677  NRT  BKK
2  TG678  BKK  CAN

## Read CSV into a Pandas Dataframe

In [4]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"

In [ ]:
df = pd.read_csv(CSV_PATH)

In [ ]:
df.head()

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [ ]:
df.tail()

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

**Quiz !!**

> แสดง 4 แถวแรก

In [ ]:
df.head(4)

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

## Column Selection

In [ ]:
df["name"]

0        Anda
1      Bordin
2    Chantana
3     Donlaya
4     Ekkasit
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [ ]:
df[["name"]]

name
0      Anda
1    Bordin
2  Chantana
3   Donlaya
4   Ekkasit
5    Fundee
6   Gitiwit
7     Harit

In [ ]:
df[["name", "gender", "age"]]

name  gender  age
0      Anda  female   39
1    Bordin    male   25
2  Chantana  female   29
3   Donlaya  female   39
4   Ekkasit    male   37
5    Fundee  female   35
6   Gitiwit    male   26
7     Harit    male   32

**Quiz !!**

> แสดงคอลัมน์ age แล้วตามด้วย name

In [ ]:
df[['age', 'name']]

age      name
0   39      Anda
1   25    Bordin
2   29  Chantana
3   39   Donlaya
4   37   Ekkasit
5   35    Fundee
6   26   Gitiwit
7   32     Harit

## Row Selection

In [ ]:
df.loc[1]

eid                   E012
name                Bordin
gender                male
department       developer
age                     25
salary             48700.0
working_years            2
birth_place         Phuket
Name: 1, dtype: object

In [ ]:
df.loc[[1]]

eid    name gender department  age   salary  working_years birth_place
1  E012  Bordin   male  developer   25  48700.0              2      Phuket

In [ ]:
df.loc[[1,2,3]]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

**Quiz !!**

> จงแสดงแถวที่ 3 แล้วตามด้วย 1

In [ ]:
df.loc[[3, 1]]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
1  E012   Bordin    male  developer   25  48700.0              2      Phuket

## Row and Column Selection (1)

In [ ]:
df.loc[1, ['name', 'age']]

name    Bordin
age         25
Name: 1, dtype: object

In [ ]:
df.loc[[1], ['name', 'age']]

name  age
1  Bordin   25

In [ ]:
df.loc[[1, 2, 3], ['name', 'age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [ ]:
df[['name', 'age']].loc[[1, 2, 3]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [ ]:
df.loc[[1, 2, 3]][['name', 'age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

**Quiz !!**

> จงแสดงคอลัมน์ age กับ name เฉพาะแถวที่ 3 กับ 1

In [ ]:
df.loc[[3, 1], ['age', 'name']]

age     name
3   39  Donlaya
1   25   Bordin

## Value Modification

In [ ]:
df[['name', 'working_years']]

name  working_years
0      Anda              4
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [ ]:
df.loc[0, 'working_years'] = 99

In [ ]:
df[['name', 'working_years']]

name  working_years
0      Anda             99
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [ ]:
df.loc[[1, 2], 'working_years'] = 999

In [ ]:
df[["name","working_years"]]

name  working_years
0      Anda             99
1    Bordin            999
2  Chantana            999
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

**Quiz !!**

> จงแก้ working_years ของคนสุดท้ายให้เป็น 55

In [ ]:
df.loc[df.index[-1], 'working_years'] = 55
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0             55     Bangkok

## Reload the Dataframe

In [ ]:
df = pd.read_csv(CSV_PATH)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Set Index

In [ ]:
df.set_index('eid')

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df.set_index('eid', inplace=True)

In [ ]:
df

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

## Row and Column Selection (2)

In [163]:
df.loc[['E011', 'E012'], ['name', 'salary']]
df.loc[['E011', 'E012']][['name', 'salary']]

name   salary
eid                  
E011    Anda  64200.0
E012  Bordin  48700.0

In [164]:
df.iloc[0]

name                  Anda
gender              female
department       developer
age                     39
salary             64200.0
working_years            4
birth_place        Bangkok
Name: E011, dtype: object

In [165]:
df.iloc[[0]] = 5

In [166]:
df.iloc[[0,1]]

name gender department  age   salary  working_years birth_place
eid                                                                    
E011       5      5          5    5      5.0              5           5
E012  Bordin   male  developer   25  48700.0              2      Phuket

In [172]:
df.iloc[[0, 1]][['name', 'gender']]
df.iloc[[0, 1]]
df.iloc[[0,1], [0,1]]

name gender
eid                
E011       5      5
E012  Bordin   male

**Quiz !!**

> จงแสดง name และ age ของ E015, E016

In [173]:
df.loc[['E015', 'E016'], ['name', 'age']]

name  age
eid               
E015  Ekkasit   37
E016   Fundee   35

## Reset Index

In [176]:
df.reset_index(inplace=True)

In [177]:
df

index   eid      name  gender department  age   salary  working_years  \
0      0  E011      Anda  female  developer   39  64200.0              4   
1      1  E012    Bordin    male  developer   25  48700.0              2   
2      2  E013  Chantana  female  developer   29  45500.0              3   
3      3  E014   Donlaya  female  marketing   39  72600.0              8   
4      4  E015   Ekkasit    male  marketing   37  80500.0              7   
5      5  E016    Fundee  female    support   35  56600.0              3   
6      6  E017   Gitiwit    male    support   26  42400.0              2   
7      7  E018     Harit    male     devops   32  67700.0              5   

  birth_place  
0     Bangkok  
1      Phuket  
2    Chonburi  
3    Chonburi  
4  Suphanburi  
5      Phuket  
6  Suphanburi  
7     Bangkok

## Reload the Dataframe



In [178]:
df = pd.read_csv(CSV_PATH)

In [179]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Range Selection

In [180]:
df.loc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [181]:
df.loc[:4]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [182]:
df.loc[4:]

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [183]:
df.loc[1:4, ['name', 'age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39
4   Ekkasit   37

In [184]:
df.iloc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

## Conditional Selection

In [185]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [186]:
df[['working_years']]

working_years
0              4
1              2
2              3
3              8
4              7
5              3
6              2
7              5

In [187]:
df['working_years'] > 3

0     True
1    False
2    False
3     True
4     True
5    False
6    False
7     True
Name: working_years, dtype: bool

In [188]:
df[df['working_years'] > 3]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [189]:
df[df['working_years'] > 3][['name', 'working_years', 'salary']]

name  working_years   salary
0     Anda              4  64200.0
3  Donlaya              8  72600.0
4  Ekkasit              7  80500.0
7    Harit              5  67700.0

In [190]:
df[(df['working_years'] > 3) & (df['salary'] > 70000)]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [192]:
df[(df['working_years'] > 3) | (df['salary'] > 70000)]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

**Quiz !!**

> จงหาคนที่เงินเดือนระหว่าง 30000 กับ 70000

In [193]:
df[(df['salary'] > 30000) & (df['salary'] < 70000)]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [194]:
df[(df['working_years'] > 3) | (df['salary'] > 70000)].iloc[[3]]

eid   name gender department  age   salary  working_years birth_place
7  E018  Harit   male     devops   32  67700.0              5     Bangkok

In [197]:
df[(df['working_years'] > 3) | (df['salary'] > 70000)].loc[[3]]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

## Column Operation

In [198]:
df['salary']

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [199]:
df['salary'] * 12

0    770400.0
1    584400.0
2    546000.0
3    871200.0
4    966000.0
5    679200.0
6    508800.0
7    812400.0
Name: salary, dtype: float64

In [200]:
df['salary'] * df['working_years'] * 12

0    3081600.0
1    1168800.0
2    1638000.0
3    6969600.0
4    6762000.0
5    2037600.0
6    1017600.0
7    4062000.0
dtype: float64

**Quiz !!**

> จงคำนวณภาษีรายปีของแต่ละคน ถ้าอัตราภาษีอยู่ที่ 10%

In [201]:
df['salary'] * 12 * 10 / 100

0    77040.0
1    58440.0
2    54600.0
3    87120.0
4    96600.0
5    67920.0
6    50880.0
7    81240.0
Name: salary, dtype: float64

## New Column

In [202]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [203]:
df['country'] = 'Thailand'

In [204]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country  
0  Thailand  
1  Thailand  
2  Thailand  
3  Thailand  
4  Thailand  
5  Thailand  
6  Thailand  
7  Thailand

In [205]:
df['salary'] * df['working_years']

0    256800.0
1     97400.0
2    136500.0
3    580800.0
4    563500.0
5    169800.0
6     84800.0
7    338500.0
dtype: float64

In [206]:
df['bonus'] = df['salary'] * df['working_years']

In [207]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0  
7  Thailand  338500.0

**Quiz !!**

> สร้างคอลัมน์ year_tax โดยคำนวณภาษีจากรายได้รายปีที่ 10%

In [208]:
df['year_tax'] = df['salary'] * 12 * 10 / 100

In [209]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0   77040.0  
1  Thailand   97400.0   58440.0  
2  Thailand  136500.0   54600.0  
3  Thailand  580800.0   87120.0  
4  Thailand  563500.0   96600.0  
5  Thailand  169800.0   67920.0  
6  Thailand   84800.0   50880.0  
7  Thailand  338500.0   81240.0

## Drop Row

In [210]:
df.drop(1)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0   77040.0  
2  Thailand  136500.0   54600.0  
3  Thailand  580800.0   87120.0  
4  Thailand  563500.0   96600.0  
5  Thailand  169800.0   67920.0  
6  Thailand   84800.0   50880.0  
7  Thailand  338500.0   81240.0

In [211]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0   77040.0  
1  Thailand   97400.0   58440.0  
2  Thailand  136500.0   54600.0  
3  Thailand  580800.0   87120.0  
4  Thailand  563500.0   96600.0  
5  Thailand  169800.0   67920.0  
6  Thailand   84800.0   50880.0  
7  Thailand  338500.0   81240.0

In [216]:
df.drop(1, inplace=True)
df.drop(2, inplace=True)

In [217]:
df

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0   77040.0  
3  Thailand  580800.0   87120.0  
4  Thailand  563500.0   96600.0  
5  Thailand  169800.0   67920.0  
6  Thailand   84800.0   50880.0  
7  Thailand  338500.0   81240.0

In [218]:
df.drop([3, 4])

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0   77040.0  
5  Thailand  169800.0   67920.0  
6  Thailand   84800.0   50880.0  
7  Thailand  338500.0   81240.0

In [219]:
df

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0   77040.0  
3  Thailand  580800.0   87120.0  
4  Thailand  563500.0   96600.0  
5  Thailand  169800.0   67920.0  
6  Thailand   84800.0   50880.0  
7  Thailand  338500.0   81240.0

**Quiz !!**

> จงลบแถวที่ 3

In [220]:
df.drop([3])

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0   77040.0  
4  Thailand  563500.0   96600.0  
5  Thailand  169800.0   67920.0  
6  Thailand   84800.0   50880.0  
7  Thailand  338500.0   81240.0

## Drop Column

In [225]:
df.drop("year_tax", axis=1)

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  Thailand  256800.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0  
7  Thailand  338500.0

In [223]:
df.drop(["country","bonus"], axis=1)

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

   year_tax  
0   77040.0  
3   87120.0  
4   96600.0  
5   67920.0  
6   50880.0  
7   81240.0

In [224]:
df

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0   77040.0  
3  Thailand  580800.0   87120.0  
4  Thailand  563500.0   96600.0  
5  Thailand  169800.0   67920.0  
6  Thailand   84800.0   50880.0  
7  Thailand  338500.0   81240.0

In [226]:
df.drop(["country","bonus"], axis=1, inplace=True)

In [227]:
df

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

   year_tax  
0   77040.0  
3   87120.0  
4   96600.0  
5   67920.0  
6   50880.0  
7   81240.0

**Quiz !!**

> จงลบคอลัมน์ age กับ name

In [228]:
df.drop(["age", "name"], axis=1)

eid  gender department   salary  working_years birth_place  year_tax
0  E011  female  developer  64200.0              4     Bangkok   77040.0
3  E014  female  marketing  72600.0              8    Chonburi   87120.0
4  E015    male  marketing  80500.0              7  Suphanburi   96600.0
5  E016  female    support  56600.0              3      Phuket   67920.0
6  E017    male    support  42400.0              2  Suphanburi   50880.0
7  E018    male     devops  67700.0              5     Bangkok   81240.0

## Reload the Dataframe

In [236]:
df = pd.read_csv(CSV_PATH)

In [230]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Sorting (1)

In [237]:
df.sort_values('salary')
df.sort_values(['salary'], inplace=True)
# df.reset_index(inplace=True, drop=True)
df

eid      name  gender department  age   salary  working_years birth_place
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
5  E016    Fundee  female    support   35  56600.0              3      Phuket
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [242]:
df.sort_values(['salary', 'department'])

eid      name  gender department  age   salary  working_years birth_place
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
5  E016    Fundee  female    support   35  56600.0              3      Phuket
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [243]:
df.sort_values('salary', ascending=False)

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

**Quiz !!**

> จงเรียงลำดับ gender จากน้อยไปมาก และ salary จากมากไปน้อย

In [ ]:
df.sort_values(['gender', 'salary'], ascending=[True, False])

eid      name  gender department  age   salary  working_years birth_place
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

## Sorting (2)

In [244]:
df.sort_values("salary", ascending=False, inplace=True)

In [245]:
df

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [246]:
df.loc[0:2]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi

In [247]:
df.iloc[0:2]

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

## Grouping (1)

In [248]:
df

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [255]:
df.groupby('department')[['salary']].mean()

salary
department         
developer   52800.0
devops      67700.0
marketing   76550.0
support     49500.0

In [256]:
df.groupby("department").max()

eid      name gender  age   salary  working_years birth_place
department                                                                
developer   E013  Chantana   male   39  64200.0              4      Phuket
devops      E018     Harit   male   32  67700.0              5     Bangkok
marketing   E015   Ekkasit   male   39  80500.0              8  Suphanburi
support     E017   Gitiwit   male   35  56600.0              3  Suphanburi

In [258]:
df.groupby(['department', 'gender'])[['age', 'salary', 'working_years']].mean()

age   salary  working_years
department gender                              
developer  female  34.0  54850.0            3.5
           male    25.0  48700.0            2.0
devops     male    32.0  67700.0            5.0
marketing  female  39.0  72600.0            8.0
           male    37.0  80500.0            7.0
support    female  35.0  56600.0            3.0
           male    26.0  42400.0            2.0

In [260]:
df.groupby("department").min()

eid     name  gender  age   salary  working_years birth_place
department                                                                
developer   E011     Anda  female   25  45500.0              2     Bangkok
devops      E018    Harit    male   32  67700.0              5     Bangkok
marketing   E014  Donlaya  female   37  72600.0              7    Chonburi
support     E016   Fundee  female   26  42400.0              2      Phuket

In [261]:
df.groupby("department").count()

eid  name  gender  age  salary  working_years  birth_place
department                                                            
developer     3     3       3    3       3              3            3
devops        1     1       1    1       1              1            1
marketing     2     2       2    2       2              2            2
support       2     2       2    2       2              2            2

In [282]:
df.groupby('department').agg(
  max_salary=('salary', 'max'),
  mean_salary=('salary', 'mean')
)

max_salary  mean_salary
department                         
developer      64200.0      52800.0
devops         67700.0      67700.0
marketing      80500.0      76550.0
support        56600.0      49500.0

In [283]:
df.groupby('department')[['age', 'salary', 'working_years']].agg(['mean', 'count'])

age         salary       working_years      
            mean count     mean count          mean count
department                                               
developer   31.0     3  52800.0     3           3.0     3
devops      32.0     1  67700.0     1           5.0     1
marketing   38.0     2  76550.0     2           7.5     2
support     30.5     2  49500.0     2           2.5     2

In [284]:
df.groupby("department")["age"].agg(["mean", "count"])

mean  count
department             
developer   31.0      3
devops      32.0      1
marketing   38.0      2
support     30.5      2

In [285]:
df.groupby("department")[["age"]].agg(["mean", "count"])

age      
            mean count
department            
developer   31.0     3
devops      32.0     1
marketing   38.0     2
support     30.5     2

In [292]:
df.groupby('department').agg({'age': ['min', 'max'], 'salary': 'mean'})

age       salary
           min max     mean
department                 
developer   25  39  52800.0
devops      32  32  67700.0
marketing   37  39  76550.0
support     26  35  49500.0

**Quiz !!**

> จงจัดกลุ่มตาม birth_place โดยแสดงค่าเฉลี่ยของ age และ ค่าสูงสุด/ต่ำสุด ของ salary

In [297]:
# df.groupby("birth_place").agg({"age":"mean", "salary":["min", "max"]})
df.groupby('birth_place').agg(
    age_avg = ('age', 'mean'),
    salary_min = ('salary', 'min'),
    salary_max = ('salary', 'max')
)

age_avg  salary_min  salary_max
birth_place                                 
Bangkok         35.5     64200.0     67700.0
Chonburi        34.0     45500.0     72600.0
Phuket          30.0     48700.0     56600.0
Suphanburi      31.5     42400.0     80500.0

## Grouping (2)

In [298]:
df_group_obj = df.groupby('department')

In [299]:
df_group_obj

In [300]:
df_group_obj[['age', 'salary', 'working_years']].mean()

age   salary  working_years
department                              
developer   31.0  52800.0            3.0
devops      32.0  67700.0            5.0
marketing   38.0  76550.0            7.5
support     30.5  49500.0            2.5

In [303]:
df_group_obj.max()

eid      name gender  age   salary  working_years birth_place
department                                                                
developer   E013  Chantana   male   39  64200.0              4      Phuket
devops      E018     Harit   male   32  67700.0              5     Bangkok
marketing   E015   Ekkasit   male   39  80500.0              8  Suphanburi
support     E017   Gitiwit   male   35  56600.0              3  Suphanburi

In [305]:
dfg = df.groupby('department').agg({
    'age': ['min', 'max'],
    'salary': 'mean'
})

In [306]:
dfg

age       salary
           min max     mean
department                 
developer   25  39  52800.0
devops      32  32  67700.0
marketing   37  39  76550.0
support     26  35  49500.0

In [307]:
dfg.columns

MultiIndex([(   'age',  'min'),
            (   'age',  'max'),
            ('salary', 'mean')],
           )

In [310]:
dfg[('age','min')]

department
developer    25
devops       32
marketing    37
support      26
Name: (age, min), dtype: int64

In [311]:
dfg[[('age','min'),('salary','mean')]]

age   salary
           min     mean
department             
developer   25  52800.0
devops      32  67700.0
marketing   37  76550.0
support     26  49500.0

In [312]:
dfg.columns

MultiIndex([(   'age',  'min'),
            (   'age',  'max'),
            ('salary', 'mean')],
           )

In [313]:
['_'.join(x) for x in dfg.columns]

['age_min', 'age_max', 'salary_mean']

In [314]:
dfg.columns = ['_'.join(x) for x in dfg.columns]

In [315]:
dfg.columns

Index(['age_min', 'age_max', 'salary_mean'], dtype='object')

In [316]:
dfg

age_min  age_max  salary_mean
department                               
developer        25       39      52800.0
devops           32       32      67700.0
marketing        37       39      76550.0
support          26       35      49500.0

In [318]:
dfg[['age_min']]

age_min
department         
developer        25
devops           32
marketing        37
support          26

In [319]:
dfg.reset_index()

department  age_min  age_max  salary_mean
0  developer       25       39      52800.0
1     devops       32       32      67700.0
2  marketing       37       39      76550.0
3    support       26       35      49500.0

In [320]:
dfg.reset_index(inplace=True)

In [321]:
dfg

department  age_min  age_max  salary_mean
0  developer       25       39      52800.0
1     devops       32       32      67700.0
2  marketing       37       39      76550.0
3    support       26       35      49500.0

## Reload the Dataset

In [322]:
df = pd.read_csv(CSV_PATH)

In [323]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Iteration

In [324]:
for index, row in df.iterrows():
  print(index)

0
1
2
3
4
5
6
7


In [325]:
for index, row in df.iterrows():
  print(index, row["eid"], row["name"], row["salary"])

0 E011 Anda 64200.0
1 E012 Bordin 48700.0
2 E013 Chantana 45500.0
3 E014 Donlaya 72600.0
4 E015 Ekkasit 80500.0
5 E016 Fundee 56600.0
6 E017 Gitiwit 42400.0
7 E018 Harit 67700.0


In [330]:
for index, row in df.iterrows():
  #row["shoud_pay_ot"] = "Something" << is not worker
  if row["salary"]>70000:
    df.loc[index,"should_pay_ot"] = "NO"
  elif row["salary"]>50000:
    df.loc[index,"should_pay_ot"] = "MAY BE"
  else:
    df.loc[index,"should_pay_ot"] = "YES"

In [329]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

## Reload the Dataset

In [17]:
df = pd.read_csv(CSV_PATH)

## Apply Function

In [6]:
np.log10(1000)

np.float64(3.0)

In [7]:
df['salary']

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [8]:
df['salary'].apply(np.log10)

0    4.807535
1    4.687529
2    4.658011
3    4.860937
4    4.905796
5    4.752816
6    4.627366
7    4.830589
Name: salary, dtype: float64

In [20]:
df["salary"].apply(np.sqrt) #slow
# np.sqrt(df['salary'])


0    253.377189
1    220.680765
2    213.307290
3    269.443872
4    283.725219
5    237.907545
6    205.912603
7    260.192237
Name: salary, dtype: float64

In [21]:
def times10(num):
  return num*10

In [22]:
times10(5)

50

In [23]:
df["age"]

0    39
1    25
2    29
3    39
4    37
5    35
6    26
7    32
Name: age, dtype: int64

In [24]:
df["age"].apply(times10)

0    390
1    250
2    290
3    390
4    370
5    350
6    260
7    320
Name: age, dtype: int64

In [25]:
df['age'] = df['age'].apply(lambda x: x * 10)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer  390  64200.0              4     Bangkok
1  E012    Bordin    male  developer  250  48700.0              2      Phuket
2  E013  Chantana  female  developer  290  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing  390  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing  370  80500.0              7  Suphanburi
5  E016    Fundee  female    support  350  56600.0              3      Phuket
6  E017   Gitiwit    male    support  260  42400.0              2  Suphanburi
7  E018     Harit    male     devops  320  67700.0              5     Bangkok

In [27]:
def consider_ot_payment(salary):
  result = ''
  if salary > 70000:
    result = 'NO'
  elif salary > 50000:
    result = 'MAY BE'
  else:
    result = 'YES'
  return result

In [28]:
consider_ot_payment(80000)

'NO'

In [29]:
consider_ot_payment(60000)

'MAY BE'

In [30]:
consider_ot_payment(30000)

'YES'

In [31]:
df["salary"].apply(consider_ot_payment)

0    MAY BE
1       YES
2       YES
3        NO
4        NO
5    MAY BE
6       YES
7    MAY BE
Name: salary, dtype: object

In [32]:
df["should_pay_ot"] = df["salary"].apply(consider_ot_payment)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer  390  64200.0              4     Bangkok   
1  E012    Bordin    male  developer  250  48700.0              2      Phuket   
2  E013  Chantana  female  developer  290  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing  390  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing  370  80500.0              7  Suphanburi   
5  E016    Fundee  female    support  350  56600.0              3      Phuket   
6  E017   Gitiwit    male    support  260  42400.0              2  Suphanburi   
7  E018     Harit    male     devops  320  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

**Quiz !!**

> จงสร้างคอลัมน์ bonus โดยการคูณ salary กับ working_years ด้วย lambda function

In [33]:
df['bonus'] = df.apply(lambda x: x['salary'] * x['working_years'], axis=1)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer  390  64200.0              4     Bangkok   
1  E012    Bordin    male  developer  250  48700.0              2      Phuket   
2  E013  Chantana  female  developer  290  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing  390  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing  370  80500.0              7  Suphanburi   
5  E016    Fundee  female    support  350  56600.0              3      Phuket   
6  E017   Gitiwit    male    support  260  42400.0              2  Suphanburi   
7  E018     Harit    male     devops  320  67700.0              5     Bangkok   

  should_pay_ot     bonus  
0        MAY BE  256800.0  
1           YES   97400.0  
2           YES  136500.0  
3            NO  580800.0  
4            NO  563500.0  
5        MAY BE  169800.0  
6           YES   84800.0  
7        MAY BE  338500.0

## Save into a CSV file

In [34]:
df.to_csv("employee2.csv")

In [36]:
pd.read_csv("employee2.csv")

Unnamed: 0   eid      name  gender department  age   salary  working_years  \
0           0  E011      Anda  female  developer  390  64200.0              4   
1           1  E012    Bordin    male  developer  250  48700.0              2   
2           2  E013  Chantana  female  developer  290  45500.0              3   
3           3  E014   Donlaya  female  marketing  390  72600.0              8   
4           4  E015   Ekkasit    male  marketing  370  80500.0              7   
5           5  E016    Fundee  female    support  350  56600.0              3   
6           6  E017   Gitiwit    male    support  260  42400.0              2   
7           7  E018     Harit    male     devops  320  67700.0              5   

  birth_place should_pay_ot     bonus  
0     Bangkok        MAY BE  256800.0  
1      Phuket           YES   97400.0  
2    Chonburi           YES  136500.0  
3    Chonburi            NO  580800.0  
4  Suphanburi            NO  563500.0  
5      Phuket        MAY BE  169800.0  
6  Suphanburi           YES   84800.0  
7     Bangkok        MAY BE  338500.0

In [37]:
df.to_csv("employee2.csv", index=False)

In [38]:
pd.read_csv("employee2.csv")

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer  390  64200.0              4     Bangkok   
1  E012    Bordin    male  developer  250  48700.0              2      Phuket   
2  E013  Chantana  female  developer  290  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing  390  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing  370  80500.0              7  Suphanburi   
5  E016    Fundee  female    support  350  56600.0              3      Phuket   
6  E017   Gitiwit    male    support  260  42400.0              2  Suphanburi   
7  E018     Harit    male     devops  320  67700.0              5     Bangkok   

  should_pay_ot     bonus  
0        MAY BE  256800.0  
1           YES   97400.0  
2           YES  136500.0  
3            NO  580800.0  
4            NO  563500.0  
5        MAY BE  169800.0  
6           YES   84800.0  
7        MAY BE  338500.0



---
https://rathachai.creatier.pro/

## つづく